// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxKO20N3q63OjvV_4uBekSbMHHJqAHbw',
    appId: '1:534287578415:web:47bff38ea41198a68c5dda',
    messagingSenderId: '534287578415',
    projectId: 'charmy-craft-studio2',
    authDomain: 'charmy-craft-studio2.firebaseapp.com',
    storageBucket: 'charmy-craft-studio2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJoRoJkMoBYVSsy8XvJY45zNRsnz3qn2c',
    appId: '1:534287578415:android:ff43cf2fcdf830088c5dda',
    messagingSenderId: '534287578415',
    projectId: 'charmy-craft-studio2',
    storageBucket: 'charmy-craft-studio2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGDO57zdV8iz5SM4W5qL51LkyaERD_Nw',
    appId: '1:534287578415:ios:43d25d2463dfa90f8c5dda',
    messagingSenderId: '534287578415',
    projectId: 'charmy-craft-studio2',
    storageBucket: 'charmy-craft-studio2.firebasestorage.app',
    iosBundleId: 'com.charmycraftstudio.charmyCraftStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGDO57zdV8iz5SM4W5qL51LkyaERD_Nw',
    appId: '1:534287578415:ios:43d25d2463dfa90f8c5dda',
    messagingSenderId: '534287578415',
    projectId: 'charmy-craft-studio2',
    storageBucket: 'charmy-craft-studio2.firebasestorage.app',
    iosBundleId: 'com.charmycraftstudio.charmyCraftStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKxKO20N3q63OjvV_4uBekSbMHHJqAHbw',
    appId: '1:534287578415:web:99719b99ef8a9ecb8c5dda',
    messagingSenderId: '534287578415',
    projectId: 'charmy-craft-studio2',
    authDomain: 'charmy-craft-studio2.firebaseapp.com',
    storageBucket: 'charmy-craft-studio2.firebasestorage.app',
  );
}
